language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
jdk:
  - openjdk6
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk6 
    - rvm: 2.0.0
      jdk: openjdk6
notifications:
  irc:
    channels:
      - "irc.freenode.org#berkshelf"
    skip_join: true
    use_notice: true
before_install:
  - sudo apt-get install -qq libarchive12 libarchive-dev
before_script:
  - git config --global user.email "ci@berkshelf.com"
  - git config --global user.name "Berkshelf"
script: 'bundle exec thor spec'
